# Site settings
course_name: # MO # MOTP #second top most item next to the logo
course_description: # "This sentence is located in _config.yml in MOTP repo. Write down a description."
course_semester: # "20" #"2024" #third top most item next to the logo

baseurl: "/MOTP" # the subpath of your site, e.g. /blog/
url: "http://jpsaha.github.io/" # the base hostname & protocol for your site

schoolname: # "1MOTP" #top most item next to the logo
schoolurl: # "https://hogwarts.edu"
twitter_username: # username 

address: | # MOTP

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Is the suggestion for updating config.yml available at https://github.com/barryclark/jekyll-now useful? 
    
# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    algebra:
        output: true
    combinatorics:
        output: true
    slides:
        output: true
    MTIS:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "algebra"
    values:
      layout: "algebrass"
  - scope:
      path: ""
      type: "combinatorics"
    values:
      layout: "combinatoric"
  - scope:
      path: ""
      type: "slides"
    values:
      layout: "slide"
  - scope:
      path: ""
      type: "MTIS"
    values:
      layout: "MTISl"
  - scope:
      path: ""
      type: "updates"
    values:
      layout: "update"
